import { useFilters } from '../useFilters'
import { Link, useParams } from 'react-router'
import { Download, Wallet, Percent, CreditCard, Undo2 } from 'lucide-react'
import { useAdmin } from '../context'
import { adminMutation } from '../api'
import { agencyBalances, csv, date, financials, labels, matches, money } from '../model'
import { DataTable, EmptyState } from '../components/DataTable'
import { Badge, DetailHeader, InfoList, PageHeader, Panel } from '../components/UI'
import { SearchInput, SelectFilter } from '../components/Filters'
import { StatCards } from '../components/StatCards'
import { ActionForm } from '../components/ActionForm'
export function FinancesSection() {
  const { data } = useAdmin(), f = useFilters(), totals = financials(data.payments)
  const balances = agencyBalances(data.payments, data.reservations)
  const reservation = (id: string) => data.reservations.find(r => r.id === id)
  const rows = data.payments.filter(p => matches(f.query, p.chargily_reference, p.id, reservation(p.reservation_id)?.reference) && (!f.get('statut') || p.status === f.get('statut')) && (!f.get('type') || p.kind === f.get('type')) && (!f.get('du') || p.created_at.slice(0, 10) >= f.get('du')) && (!f.get('au') || p.created_at.slice(0, 10) <= f.get('au'))).sort((a, b) => b.created_at.localeCompare(a.created_at))
  function exportCsv() {
    const text = csv([['Transaction', 'Réservation', 'Référence Chargily', 'Source', 'Type', 'Statut', 'Montant DZD', 'Commission DZD', 'Remboursé DZD', 'Commission remboursée DZD', 'Versé agence DZD', 'Création', 'Confirmation'], ...rows.map(p => [p.id, reservation(p.reservation_id)?.reference, p.chargily_reference, p.source, labels[p.kind], labels[p.status], (p.amount_cents / 100).toFixed(2), (p.commission_cents / 100).toFixed(2), (p.refunded_cents / 100).toFixed(2), (p.refunded_commission_cents / 100).toFixed(2), (p.agency_transferred_cents / 100).toFixed(2), p.created_at, p.confirmed_at])])
    const url = URL.createObjectURL(new Blob([text], { type: 'text/csv;charset=utf-8;' })), link = document.createElement('a')
    link.href = url; link.download = 'sb-rental-transactions.csv'; link.click(); setTimeout(() => URL.revokeObjectURL(url), 1000)
  }
  return <><PageHeader title="Finances" description="Encaissements, commissions et reversements. Chaque montant vient d’une transaction enregistrée."><button className="bo-secondary" onClick={exportCsv}><Download size={17} /> Exporter CSV</button></PageHeader><StatCards items={[
    { label: 'Total payé', value: money(totals.paid), note: 'Paiements confirmés, avant remboursements', icon: Wallet, accent: true }, { label: 'Acomptes encaissés', value: money(totals.deposit), note: 'Acomptes de 10 %, nets de remboursements', icon: CreditCard }, { label: 'Commission SB Rental', value: money(totals.commission), note: 'Commission encaissée nette', icon: Percent }, { label: 'Montants dus aux agences', value: money(balances.payable), note: balances.recoverable > 0 ? `À récupérer séparément : ${money(balances.recoverable)}` : 'Part encaissée, nette des versements' }, { label: 'Paiements en attente', value: money(totals.pending) }, { label: 'Paiements remboursés', value: money(totals.refunded), icon: Undo2 },
  ]} /><Panel title="Historique des transactions" note="Indicateurs cumulés. L’export respecte les filtres de l’historique."><div className="bo-filters"><SearchInput value={f.query} onChange={v => f.set('q', v)} placeholder="Référence Chargily ou réservation" /><SelectFilter label="Statut" value={f.get('statut')} onChange={v => f.set('statut', v)} options={{ pending: 'En attente', confirmed: 'Confirmé', failed: 'Échoué', refunded: 'Remboursé' }} /><SelectFilter label="Type" value={f.get('type')} onChange={v => f.set('type', v)} options={{ deposit: 'Acompte', balance: 'Solde' }} /><label className="bo-select"><span>Créé depuis</span><input type="date" value={f.get('du')} onChange={e => f.set('du', e.target.value)} /></label><label className="bo-select"><span>Jusqu’au</span><input type="date" value={f.get('au')} onChange={e => f.set('au', e.target.value)} /></label></div><DataTable key={f.key} rows={rows} label="Transactions" empty="Aucune transaction enregistrée" columns={[
    { label: 'Transaction', render: p => <Link className="bo-link" to={`/admin/finances/${p.id}`}>{p.chargily_reference || p.id.slice(0, 8)}<small>{labels[p.source]}</small></Link> }, { label: 'Réservation', render: p => <Link to={`/admin/reservations/${p.reservation_id}`}>{reservation(p.reservation_id)?.reference ?? '—'}</Link> }, { label: 'Type', render: p => labels[p.kind] }, { label: 'Montant', render: p => money(p.amount_cents) }, { label: 'Commission', render: p => money(p.commission_cents) }, { label: 'Remboursé', render: p => money(p.refunded_cents) }, { label: 'Statut', render: p => <Badge value={p.status} /> }, { label: 'Création', render: p => date(p.created_at) },
  ]} /></Panel><p className="bo-footnote">Les paiements sont confirmés par leur source côté serveur. Ajouter une note dans le back-office ne confirme ni ne rembourse un paiement. Les espèces remises directement à l’agence n’apparaissent que si elles ont été enregistrées.</p></>
}
export function PaymentDetail() {
  const { id } = useParams(), { data, refresh } = useAdmin(), p = data.payments.find(p => p.id === id)
  if (!p) return <EmptyState title="Paiement introuvable" />
  return <><DetailHeader back="/admin/finances" title={p.chargily_reference || `Transaction ${p.id.slice(0, 8)}`} description="Une trace financière, avec son origine et son statut." /><div className="bo-detail-grid"><Panel title="Transaction" action={<Badge value={p.status} />}><InfoList items={[["Référence Chargily", p.chargily_reference ?? 'Non applicable'], ['Source', labels[p.source]], ['Type', labels[p.kind]], ['Montant', money(p.amount_cents)], ['Commission affectée', money(p.commission_cents)], ['Remboursement', money(p.refunded_cents)], ['Versé à l’agence', money(p.agency_transferred_cents)], ['Création', date(p.created_at, true)], ['Confirmation', p.confirmed_at ? date(p.confirmed_at, true) : 'En attente'], ['Réservation', <Link key="reservation" className="bo-link" to={`/admin/reservations/${p.reservation_id}`}>Consulter la réservation →</Link>]]} /></Panel><Panel title="Note administrative" note="La modification sera journalisée avec votre compte."><ActionForm key={p.updated_at} action={async form => { await adminMutation('admin_note_payment', { payment_id: p.id, expected_updated_at: p.updated_at, note: String(form.get('note') ?? '') }); refresh() }}><label>Note de suivi<textarea name="note" rows={5} defaultValue={p.admin_note} maxLength={2000} /></label><p className="bo-help">Le montant, la référence et le statut du paiement sont consultables uniquement.</p></ActionForm></Panel></div></>
}
